### PR TITLE
Fix sample code to work with SWResample 0.2

### PR DESCRIPTION
**Pull request by sionide21**
The previous code failed to compile with the following error. 

```
== Compilation error in file lib/first_membrane_project/pipeline.ex ==
** (KeyError) key :source_caps not found
    expanding struct: Membrane.Element.FFmpeg.SWResample.Converter.__struct__/1
    lib/first_membrane_project/pipeline.ex:8: Project.Pipeline.handle_init/1
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

### CODE REVIEW

**Comment by bblaszkow06** [comment]
Thank you for your contribution!
